animal = "  chanchito feliz  "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("ct"))
print(animal.replace("an","en"))
print("chito" in animal)